const questions = [

{
    question: "What is the capital of India?",
    options: ["Mumbai", "Delhi", "Hyderabad", "Chennai"],
    answer: "Delhi"
},

{
    question: "Which language runs in browser?",
    options: ["Java", "C", "Python", "JavaScript"],
    answer: "JavaScript"
},

{
    question: "What does HTML stand for?",
    options: [
        "Hyper Text Markup Language",
        "High Text Machine Language",
        "Hyper Tool Multi Language",
        "None"
    ],
    answer: "Hyper Text Markup Language"
},

{
    question: "2 + 2 = ?",
    options: ["3", "4", "5", "6"],
    answer: "4"
},

{
    question: "CSS is used for?",
    options: [
        "Styling",
        "Database",
        "Backend",
        "Server"
    ],
    answer: "Styling"
}

];